find_package(PCL REQUIRED)
find_package(OpenCV 3 REQUIRED)
find_package(VTK REQUIRED)
find_package(Eigen REQUIRED)
find_package(Boost 1.40 COMPONENTS program_options REQUIRED)
find_package(Glew REQUIRED)